[llms.embedding]
"stapi host" = "http://${HOST}:${PORT}"

[llms.chat]
"host" = "http://${HOST}:${PORT}"
context = 3000

[story.one]
id = 62270
"relevance question" = """
	Which scenes depict Luna and another character having a romantic or intimate moment?
	"""
"analysis question" = "Describe each character's relationship in the story."
