[llms.embedding]
"stapi host" = "http://${HOST}:${PORT}"

[llms.chat]
"ollama host" = "http://${HOST}:${PORT}"
"ollama model" = "falcon3:1b-instruct-fp16"
# alt: hf.co/bartowski/Llama-3.2-1B-Instruct-GGUF:F16
context = 7000

[story.one]
id = 62270
"relevance question" = """
	Which scenes depict Luna and another character having a romantic or intimate moment?
	"""
"analysis question" = "Describe each character's relationship in the story."
